### ISSUE TITLE
Table missing

### ISSUE THREAD

**Issue by migsilva95** [iptomar/projectary-bd#54] opened 2017-04-06 15:11 UTC
There is 2 procedures, API_InsertNewSchoolEntity and DEPRACATED_InsertNewSchoolEntity, inserting into table SchoolEntity but there is no table SchoolEntity.

**Comment by palfaiate** [comment] 2017-04-07 16:25
That table was deprecated

**Comment by asantos3** [comment] 2017-04-07 17:06
That doesn't solve the issue at all, don't close issues if the problem is still there.
There's two procedures using an non existing table.
Please close the issues with the reference to where it was fixed, like a reference to the pull request or to the commit itself (like #56 or 684f6f0).

**Closed as completed** 2017-04-28 20:44 UTC
